on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with: 
            node-version: "14.x"

        - name: Install dependencies
          run: npm install
 
        - name: Install jest
          run: npm install jest

        - name: Install express
          run: npm install express        
          
        - name: Allow from root -1 
          run: npm config set user 0

          
        - name: Allow from root -2
          run: npm config set unsafe-perm true
          
        - name: Run test
          run: npm test
